# Generated by Django 3.2.10 on 2024-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='coadmin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
