# Generated by Django 3.2.10 on 2024-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_appnotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coadmin',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='coadmin',
            name='otp_secret_key',
        ),
        migrations.AddField(
            model_name='coadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this co-admin belongs to.', related_name='coadmin_set', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='coadmin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='coadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this co-admin.', related_name='coadmin_set', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
