# Generated by Django 3.2.10 on 2024-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240927_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='road_name',
            field=models.TextField(default='road name'),
        ),
    ]
