# Generated by Django 3.2.10 on 2024-10-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
