# Generated by Django 3.2.10 on 2024-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboy', '0002_deliveryboy_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
