# Generated by Django 3.2.10 on 2024-10-26 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dboy', '0003_deliveryboy_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
