# Generated by Django 3.2.10 on 2024-10-26 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dboy', '0005_orderassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignment',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='delivery_boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dboy.deliveryboy'),
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('WAITING FOR CONFIRMATION', 'Waiting for confirmation'), ('CONFIRMED', 'Confirmed'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'delivered'), ('REJECTED', 'rejected')], default='OUT FOR DELIVERY', max_length=100),
        ),
    ]
