# Generated by Django 3.2.10 on 2024-10-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboy', '0006_auto_20241026_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
