# Generated by Django 3.2.10 on 2024-09-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='total_price',
        ),
    ]
