# Generated by Django 3.2.10 on 2024-09-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20240902_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
