# Generated by Django 5.1 on 2024-10-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_auto_20240917_1039"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("Online", "Online Payment")],
                default="COD",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_ids",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="product_names",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
    ]
