# Generated by Django 5.1 on 2024-10-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_remove_order_cart_remove_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("PACKED", "packed"),
                    ("OUT FOR DELIVERY", "out for delivery"),
                    ("DELIVERED", "delivered"),
                ],
                default="CONFIRMED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("Online", "Online Payment")],
                max_length=100,
            ),
        ),
    ]
