# Generated by Django 3.2.10 on 2024-10-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_status_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
