# Generated by Django 3.2.10 on 2024-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PACKED', 'packed'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'delivered')], default='CONFIRMED', max_length=20),
        ),
    ]
