# Generated by Django 3.2.10 on 2024-10-02 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cart_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='unique_order_serial',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
