# Generated by Django 3.2.10 on 2024-10-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_order_unique_order_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING FOR CONFIRMATION', 'Waiting for confirmation'), ('CONFIRMED', 'Confirmed'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'delivered')], default='WAITING FOR CONFIRMATION', max_length=100),
        ),
    ]
