# Generated by Django 3.2.10 on 2024-10-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_weights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
