# Generated by Django 3.2.10 on 2024-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20241004_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
