# Generated by Django 5.0.6 on 2024-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_measurement',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('l', 'Liters')], default='g', max_length=2),
        ),
    ]
