# Generated by Django 3.2.10 on 2024-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular_product',
            field=models.BooleanField(default=False),
        ),
    ]
