# Generated by Django 3.2.10 on 2024-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240831_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weights',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_measurement',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('l', 'Liters')], default='g', max_length=2),
        ),
    ]
