# Generated by Django 3.2.10 on 2024-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240831_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weights',
            field=models.TextField(default='[]', help_text='Store different weights, quantities, and prices in JSON format'),
        ),
    ]
