# Generated by Django 3.2.10 on 2024-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weights',
            field=models.TextField(default='[]', help_text='Store different weights in JSON format'),
        ),
    ]
