# Generated by Django 3.2.10 on 2024-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_measurement',
            field=models.CharField(max_length=100),
        ),
    ]
