# Generated by Django 3.2.10 on 2024-08-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weights',
            field=models.JSONField(default=list, help_text='Store different weights with their respective prices in a list of dictionaries'),
        ),
    ]
