# Generated by Django 3.2.10 on 2024-09-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_category',
            new_name='SubCategories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sub_category',
            new_name='sub_category',
        ),
    ]
