# Generated by Django 3.2.10 on 2024-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20240912_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weights',
            field=models.JSONField(help_text='Store different weights with their respective prices, either as a list or a dictionary'),
        ),
    ]
