# Generated by Django 3.2.10 on 2024-09-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True, help_text='Enable to show as in stock, disable to show as out of stock'),
        ),
    ]
