# Generated by Django 3.2.10 on 2024-09-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_is_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Enable_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='Enable_subcategory',
            field=models.BooleanField(default=True),
        ),
    ]
