# Generated by Django 3.2.10 on 2024-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_weight_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_measurement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weights',
            field=models.JSONField(help_text='Store different weights with their respective prices, quantities, and stock status as a dictionary'),
        ),
    ]
