# Generated by Django 3.2.10 on 2024-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20241009_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
