# Generated by Django 3.2.10 on 2024-10-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_heading', models.CharField(max_length=100)),
                ('Home_title', models.CharField(max_length=100)),
                ('Home_sub_title', models.CharField(max_length=100)),
                ('Home_image', models.ImageField(upload_to='poster_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_heading', models.CharField(max_length=100)),
                ('poster_title', models.CharField(max_length=100)),
                ('poster_sub_title', models.CharField(max_length=100)),
                ('poster_image', models.ImageField(upload_to='poster_images/')),
            ],
        ),
    ]
