# Generated by Django 3.2.10 on 2024-10-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_homepageimage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='products',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
