# Generated by Django 3.2.10 on 2024-11-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_homepageimage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whole_sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
