# Generated by Django 3.2.10 on 2024-11-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_whole_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
