# Generated by Django 5.1.3 on 2024-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
